### ISSUE TITLE
请问Xcode下如何构建？

### ISSUE THREAD

**Issue by jackhub** [netwarm007/GameEngineFromScratch#12]
把代码全部拉取下来后，执行./build-xcode.sh，每次都报错：

...
-- CMAKE_RANLIB: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
-- CMAKE_CROSSCOMPILING: FALSE
-- TARGET_ARCH: x86_64
-- XG_LIBRARY: XG_LIBRARY-NOTFOUND
-- OPENDDL_LIBRARY: OPENDDL_LIBRARY-NOTFOUND
-- OPENGEX_LIBRARY: OPENGEX_LIBRARY-NOTFOUND
-- BULLET_COLLISION_LIBRARY: BULLET_COLLISION_LIBRARY-NOTFOUND
-- BULLET_DYNAMICS_LIBRARY: BULLET_DYNAMICS_LIBRARY-NOTFOUND
-- BULLET_LINEARMATH_LIBRARY: BULLET_LINEARMATH_LIBRARY-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BULLET_COLLISION_LIBRARY
    linked by target "BulletPhysics" in directory /Users/jackjhu/Project/Recent/GameEngineFromScratch/Physics/Bullet
BULLET_DYNAMICS_LIBRARY
    linked by target "BulletPhysics" in directory /Users/jackjhu/Project/Recent/GameEngineFromScratch/Physics/Bullet
BULLET_LINEARMATH_LIBRARY
    linked by target "BulletPhysics" in directory /Users/jackjhu/Project/Recent/GameEngineFromScratch/Physics/Bullet
OPENDDL_LIBRARY
    linked by target "Common" in directory /Users/jackjhu/Project/Recent/GameEngineFromScratch/Framework/Common
OPENGEX_LIBRARY
    linked by target "Common" in directory /Users/jackjhu/Project/Recent/GameEngineFromScratch/Framework/Common
XG_LIBRARY
    linked by target "Common" in directory /Users/jackjhu/Project/Recent/GameEngineFromScratch/Framework/Common

-- Configuring incomplete, errors occurred!
See also "/Users/jackjhu/Project/Recent/GameEngineFromScratch/build/CMakeFiles/CMakeOutput.log".
See also "/Users/jackjhu/Project/Recent/GameEngineFromScratch/build/CMakeFiles/CMakeError.log".

**Comment by netwarm007** [comment]
根目录下有几个诸如build_bullet.sh、build_opengex.sh等的脚本要先执行。
