### ISSUE TITLE
请问cmake生成的vs项目调试时无法自动加载pdb要怎样设置?

### ISSUE THREAD

**Issue by RPG3D** [netwarm007/GameEngineFromScratch#17]
我目前没有用clang编译。用vs编译出来的exe单独运行没有报错，调试就崩溃，断点无法命中。需要在cmake中设置调试符合相关的吗？

**Comment by netwarm007** [comment]
除了设置类型为Debug之外，没有什么特别的设置。

**Comment by RPG3D** [comment]
[我是设置的Debug，但是断点无法命中。感觉跟项目组织方式有关系；main函数在一个Common模块，测试模块没有主函数（链接Common模块），测试模块的初始化函数和Common的主函数断点都无法命中。
[https://github.com/RPG3D/NextEngine/blob/master/Documents/Bug/NoBP.png](url)

**Comment by netwarm007** [comment]
也许项目之间没有设置参照关系吧。
