### ISSUE TITLE
Ubuntu部分编译失败和OpenGl运行崩溃

### ISSUE THREAD

**Issue by lishaojiang** [netwarm007/GameEngineFromScratch#21]
感谢您的代码，学习受教了。
1.我在windows平台编译通过了，也可以运行。
2.在Ubuntu 20下，也安装各种库后，只有最后的最后，**Test/BulletTest.cpp** 的25行
    btCollisionShape* groundShape = **new btStaticPlaneShape(btVector3(0.0f, 1.0f, 0.0f), 1);**编译失败，提示：undefined reference to `btStaticPlaneShape::btStaticPlaneShape(btVector3 const&, double)'
collect2: error: ld returned 1 exit status
另外一个工程：**Game/Billiard**也是同样的错误。
我看了一下大约是部分内容引用float,部分引用了double，不知怎么修改。
3.我临时屏掉这两个工程，编译通过，我用Viewer工程进行测试，发现运行时Initialize崩溃，崩到：GameEngineFromScratch/Platform/Linux/OpenGLApplication.cpp的156行，**int default_screen = DefaultScreen(m_pDisplay);**，我也分析了一下，这个时间理论上m_pDisplay = nullptr,理论上强转到结构体，的确会崩。
下面是堆栈，刚启动，比较简单，我这边必现的。
My::OpenGLApplication::CreateMainWindow(My::OpenGLApplication * const this) (/GameEngineFromScratch/Platform/Linux/OpenGLApplication.cpp:156)
My::BaseApplication::Initialize(My::BaseApplication * const this) (/GameEngineFromScratch/Framework/Common/BaseApplication.cpp:20)
My::OpenGLApplication::Initialize(My::OpenGLApplication * const this) (/GameEngineFromScratch/Platform/Linux/OpenGLApplication.cpp:50)
main(int argc, char ** argv) (/GameEngineFromScratch/Framework/Common/main.cpp:52)

谢谢，祝好。

**Comment by netwarm007** [comment]
需要在图形界面下启动。另外master当中的Linux版本的确有些问题，今天刚刚修复。
