### ISSUE TITLE
git clone 报错 error: external filter git-lfs smudge -- %f failed 2

### ISSUE THREAD

**Issue by azyl99** [netwarm007/GameEngineFromScratch#4]
报错信息
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed

下面这个链接的解释是大文件上传没有成功
http://www.hahack.com/work/enterprise-class-git-version-control-5/

**Comment by netwarm007** [comment]
不是。这是因为github的git lfs是基于amazon S3的。而国内到amazon S3的线路奇差。你可以执行git lfs fetch --all来下载所有大文件到本地，就可以修复这个问题。只不过下载真的是很慢。以后有时间了我看看是否能将LFS Server转移到国内。
