### ISSUE TITLE
为什么我下载的项目里只有一个tag  v0.0

### ISSUE THREAD

**Issue by xl18zwd** [netwarm007/GameEngineFromScratch#6]
如题，应该是每章代码都有tag吧

**Comment by netwarm007** [comment]
不是。每篇的代码都是用branch的形式保存的。

发自我的华为手机

-------- 原始邮件 --------
主题：[netwarm007/GameEngineFromScratch] 为什么我下载的项目里只有一个tag v0.0 (#6)
发件人：zsq
收件人：netwarm007/GameEngineFromScratch
抄送：Subscribed


如题，应该是每章代码都有tag吧

―

**Comment by netwarm007** [comment]
关闭

**Comment by xl18zwd** [comment]
看到了，很多对应的branch
