### ISSUE TITLE
有个有疑问的地方

### ISSUE THREAD

**Issue by zhangximing** [netwarm007/GameEngineFromScratch#7]
void* My::MemoryManager::Allocate(size_t size, size_t alignment)
{
    uint8_t* p;
    size += alignment;
    Allocator* pAlloc = LookUpAllocator(size);
    if (pAlloc)
        p = reinterpret_cast<uint8_t*>(pAlloc->Allocate());
    else
        p = reinterpret_cast<uint8_t*>(malloc(size));

    p = reinterpret_cast<uint8_t*>(ALIGN(reinterpret_cast<size_t>(p), alignment));
    
    return static_cast<void*>(p);
}

您好，这里有个地方我有点疑问，不知道对不对。
 p = reinterpret_cast<uint8_t*>(ALIGN(reinterpret_cast<size_t>(p), alignment));
这里对Allocator返回出来的指针可能会做对齐的移动操作，但是在free的时候没有看到移回之前的位置，不知道会不会有问题

**Comment by netwarm007** [comment]
不会有问题。因为这里的分配和后面的释放都是按照block为单位的，而不是依照具体的地址。

-------- 原始邮件 --------
主题：[netwarm007/GameEngineFromScratch] 有个有疑问的地方 (#7)
发件人：zhangximing
收件人：netwarm007/GameEngineFromScratch
抄送：Subscribed


void* My::MemoryManager::Allocate(size_t size, size_t alignment)
{
uint8_t* p;
size += alignment;
Allocator* pAlloc = LookUpAllocator(size);
if (pAlloc)
p = reinterpret_cast<uint8_t*>(pAlloc->Allocate());
else
p = reinterpret_cast<uint8_t*>(malloc(size));

p = reinterpret_cast<uint8_t*>(ALIGN(reinterpret_cast<size_t>(p), alignment));

return static_cast<void*>(p);


}

您好，这里有个地方我有点疑问，不知道对不对。
p = reinterpret_cast<uint8_t*>(ALIGN(reinterpret_cast<size_t>(p), alignment));
这里对Allocator返回出来的指针可能会做对齐的移动操作，但是在free的时候没有看到移回之前的位置，不知道会不会有问题

―

**Comment by zhangximing** [comment]
感谢您的回复，不知道我理解错误没有。我指的是这里的p经对齐移动后， Allocator::Free回到 FreeList时，我理解的是free回去的block的起始指针位置变了，如果是debug模式下填充 FillFreeBlock，可能会操作到其他block的数据

**Comment by netwarm007** [comment]
也许是的。你可以实际验证一下。期待你的merge request
