### ISSUE TITLE
Linux下直接编译失败，感觉是ispc没有编译，但是看您专栏好像也没提到

### ISSUE THREAD

**Issue by LonelySilen** [netwarm007/GameEngineFromScratch#8]
Scanning dependencies of target GeomMathLib
[  1%] Building DivByElement
No such file or directory
Framework/GeomMath/ispc/CMakeFiles/GeomMathLib.dir/build.make:138: recipe for target 'Framework/GeomMath/ispc/DivByElement.o' failed
make[2]: *** [Framework/GeomMath/ispc/DivByElement.o] Error 1
CMakeFiles/Makefile2:1197: recipe for target 'Framework/GeomMath/ispc/CMakeFiles/GeomMathLib.dir/all' failed
make[1]: *** [Framework/GeomMath/ispc/CMakeFiles/GeomMathLib.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by netwarm007** [comment]
比较有可能是没有安装git-lfs。你看一下你的External/Linux/bin目录当中的ispc是不是很小的一个文件，打开其实是一个文本文件？如果是，说明就是这个问题。
